<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-11-30 at 04:35:34.
 */
require '../DAOCliente.php';
class DAOClienteTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DAOCliente
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DAOCliente;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testDesconectar() {
        $this->assertEquals(
                "close"
                , $this->object->getDesconectar()                
                );
    }
    public function testConectar() {
        $this->assertEquals(
                "conectado"
                , $this->object->getConectar()                
                );
    }  
    
    public function testGetTabla() {
        $this->assertEquals(
                "<tr><td>.['idcliente']
                <td>['email']</td>
                <td>['clave']</td>
                </tr>"
                , $this->object->getTabla()                
                );    
    }
    public function testInsertar() {
        $this->assertEquals(
                "Cliente registrado"
                , $this->object->Insertar()                
                );        
    }

}
