<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-11-30 at 04:47:24.
 */
require '../Producto.php';
class ProductoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Producto
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Producto;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Producto::getCodigo
     * @todo   Implement testGetCodigo().
     */
    public function testGetCodigo() {
        $this->assertEquals(
                1
                , $this->object->getCodigo()                
                );
    }

    public function testGetNombre() {
        $this->assertEquals(
                "tarjeta"
                , $this->object->getNombre()                
                );
    }
    public function testGetDescripcion() {
       $this->assertEquals(
                "tarjeta moderna color negro"
                , $this->object->getDescripcion()                
                );
    }
    public function testGetPrecio() {
        $this->assertEquals(
                12.00
                , $this->object->getPrecio()                
                );
    }
    public function testGetTipo() {
        $this->assertEquals(
                "jpg"
                , $this->object->getTipo()                
                );
    }
}
